# Generated by Django 4.1.7 on 2023-03-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_temp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='month',
            field=models.TextField(),
        ),
    ]
